### PR TITLE
Use the home key instead of the power key to turn on

### PR DESCRIPTION
**Pull request by JeffLIrion**
Please merge https://github.com/happyleavesaoc/python-firetv/pull/75 first.

### CODE REVIEW

**Comment by carstenschroeder** [comment]
This doesn't work with my fire tv. The home key doesn't turn it on. I need to send power key to wake it up. After that a home key is needed to turn on attached TV.

**Comment by JeffLIrion** [comment]
> This doesn't work with my fire tv. The home key doesn't turn it on. I need to send power key to wake it up. After that a home key is needed to turn on attached TV.

How did you test this? If your device is off and you press the Home button on your remote, does it turn on?

**Comment by carstenschroeder** [comment]
Yes, with the remote it works of course. But not with HOME key sent by ADB. I tested it in HA with the new service for the firetv platform. 

Does it work on your side?

**Comment by JeffLIrion** [comment]
Yeah, it works perfectly for turning on my Fire TV stick, which in turn turns on my TV through CEC. If you change the HA `turn_on` command to use `self.firetv.home()` instead of `self.firetv.power()`, that doesn't work for you?

**Comment by carstenschroeder** [comment]
No, my Fire TV 2nd gen. does not turn on this way.

**Comment by carstenschroeder** [comment]
The following combination works though:

self.firetv.turn_on()
self.firetv.home()

**Comment by JeffLIrion** [comment]
That's very odd. I'll close this PR for now and think about the best way to handle this.

**Comment by JeffLIrion** [comment]
I think a modification like this might be the best way to handle this specific issue. The reason for modifying the `_key` method is because I've found that minimizing the number of ADB commands sent in short succession improves stability. 

```python
    def _key(self, *keys):
        """ Send one or more key events to device.
        :param keys: Key constants.
        """
        self._adb_shell('input keyevent {0}'.format(' && input keyevent '.join(keys)))

    def turn_on(self):
        """ Send power and home actions if device is off. """
        if not self.screen_on:
            self._key(POWER, HOME)
```

**Comment by JeffLIrion** [comment]
Even more compact, but more confusing: 1 ADB command to check if the power is on and, if not, send the POWER and HOME commands. 

```python
    def turn_on(self):
        """ Send power and home actions if device is off. """
        self._adb_shell("dumpsys power | grep 'Display Power' | grep -q 'state=ON' && echo 'already on' || (input keyevent 26 && input keyevent 3)")
```

**Pull request closed without merging**
