### PR TITLE
Feature/start and stop apps

### PR DESCRIPTION
**Pull request by juliangeiges**

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Looks good, thanks!

**Comment by Bart274** [comment]
Awesome PR! Now I just need to reinstall it again ?

Op 13 okt. 2016 om 19:27 heeft happyleavesaoc <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Looks good, thanks!

##

**Comment by juliangeiges** [comment]
yep, you only need to reinstall it.

**Comment by happyleavesaoc** [comment]
I'll be fixing another bug and then cutting a new pypi release as well.

**Comment by juliangeiges** [comment]
BTW: What do you think about implementing some persistence? Adding different Fire TV Devices every reboot needs a lot of automation in my HA-System.

**Comment by happyleavesaoc** [comment]
I think that could work. If you open an Issue, it could be discussed more there.

**Pull request merged**
