### PR TITLE
Version 1.0.8

### PR DESCRIPTION
**Pull request by JeffLIrion**
This is the follow-up to https://github.com/happyleavesaoc/python-firetv/pull/77. If you'd like me to split this into multiple pull requests or clean up the commits, I can do that.

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
I can add you as a collaborator (push access), if you'd like.

**Comment by JeffLIrion** [comment]
That would be great, thanks! 

Also, could you please push a new release to pypi when you get a chance.

**Comment by JeffLIrion** [comment]
Could you please push a new release to pypi. Or if you don't mind adding me to the pypi project (same username), then I could do it.

**Comment by happyleavesaoc** [comment]
Pushed `1.0.8` to pypi and added you as a maintainer. Thanks!

**Pull request merged**
