### PR TITLE
Added support for adb_shell, since adb is horked

### PR DESCRIPTION
**Pull request by CodeMonk**
This adds support for using https://github.com/JeffLIrion/adb_shell since python-adb is no longer supported, and didn't work for me.

### CODE REVIEW

**Comment by JeffLIrion** [comment]
[`androidtv`](https://github.com/JeffLIrion/python-androidtv) utilizes `adb-shell` and supports Fire TV devices. It abstracts the ADB methods into two classes: `AdbPython` and `AdbServer`. This makes the code easier to modify (if necessary) and test, and IMO it is the proper way to implement the ADB-related portions of the code.

**Comment by CodeMonk** [comment]
> [`androidtv`](https://github.com/JeffLIrion/python-androidtv) utilizes `adb-shell` and supports Fire TV devices. It abstracts the ADB methods into two classes: `AdbPython` and `AdbServer`. This makes the code easier to modify (if necessary) and test, and IMO it is the proper way to implement the ADB-related portions of the code.

Thanks for that! I'll check it out. I'm trying to make a routine for Alexa, and I'm super annoyed that you can't use their firetv integration in a routine.

**Comment by JeffLIrion** [comment]
How are you going to call Python code as part of your Alexa routine? Are you using a home automation platform?

**Comment by CodeMonk** [comment]
I hadn't decided yet. I only had a basic webservice running, and hadn't added anything to alexa yet. I'm looking at home-automation now.

**Comment by CodeMonk** [comment]
Welp, it's working. Now I get to decide if I want to pay $5/month, or create my own web service. I'll prolly pony up the $5.

**Pull request merged**
